{
 "title": "Mochiko Infra Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "ICX 8200 - Core Swtiches Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Switch 1 - Active Ports",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "/ 24" } },
   "targets": [
    {
     "expr": "count(\n  (\n    max_over_time(\n      ifOperStatus{\n        job=\"ruckus-core-stack\",\n        instance=\"192.0.100.1\"\n      }[5m]\n    ) == 1\n  )\n  and on (ifIndex, instance)\n  ifName{\n    job=\"ruckus-core-stack\",\n    instance=\"192.0.100.1\",\n    ifName=~\"ethernet 1/1/.*\"\n  }\n)\nor vector(0)",
     "legendFormat": "__auto",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"switch_port_metrics\" and\n    r._field == \"status\" and\n    r.switch == \"icx8100\"\n  )\n  |> group(columns: [\"port\"])\n  |> last()\n  |> filter(fn: (r) => r._value == 1)\n  |> group()\n  |> count()\n"
    }
   ]
  },
  {
   "title": "Swich 1 - Down Ports",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "/ 24" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  (\n    max_over_time(\n      ifOperStatus{\n        job=\"ruckus-core-stack\", \n        instance=\"192.0.100.1\"\n      }[5m]\n    ) == 0\n  )\n  and on (ifIndex, instance)\n  ifName{\n    job=\"ruckus-core-stack\",\n    instance=\"192.0.100.1\",\n    ifName=~\"ethernet 1/1/.*\"\n  }\n)\nor vector(0)",
     "legendFormat": "__auto",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"switch_port_metrics\" and\n    r._field == \"status\" and\n    r.switch == \"icx8100\"\n  )\n  |> group(columns: [\"port\"])\n  |> last()\n  |> filter(fn: (r) => r._value == 0)\n  |> group()\n  |> count()\n"
    }
   ]
  },
  {
   "title": "Switch 1 - Empty Ports",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "/ 24" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  (\n    max_over_time(\n      ifOperStatus{\n        job=\"ruckus-core-stack\",\n        instance=\"192.0.100.1\"\n      }[5m]\n    ) == 2\n  )\n  and on (ifIndex, instance)\n  ifName{\n    job=\"ruckus-core-stack\",\n    instance=\"192.0.100.1\",\n    ifName=~\"ethernet 1/1/.*\"\n  }\n)\nor vector(0)",
     "legendFormat": "__auto",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"switch_port_metrics\" and\n    r._field == \"status\" and\n    r.switch == \"icx8100\"\n  )\n  |> group(columns: [\"port\"])\n  |> last()\n  |> filter(fn: (r) => r._value == 2)\n  |> group()\n  |> count()\n"
    }
   ]
  },
  {
   "title": "Switch 2 - Active Ports",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "/ 24" } },
   "targets": [
    {
     "expr": "count(\n  (\n    max_over_time(\n      ifOperStatus{\n        job=\"ruckus-core-stack\",\n        instance=\"192.0.100.1\"\n      }[5m]\n    ) == 1\n  )\n  and on (ifIndex, instance)\n  ifName{\n    job=\"ruckus-core-stack\",\n    instance=\"192.0.100.1\",\n    ifName=~\"ethernet 2/1/.*\"\n  }\n)\nor vector(0)",
     "legendFormat": "__auto",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"switch_port_metrics\" and\n    r._field == \"status\" and\n    r.switch == \"icx8100\"\n  )\n  |> group(columns: [\"port\"])\n  |> last()\n  |> filter(fn: (r) => r._value == 1)\n  |> group()\n  |> count()\n"
    }
   ]
  },
  {
   "title": "Swich 1 - Down Ports",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "/ 24" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  (\n    max_over_time(\n      ifOperStatus{\n        job=\"ruckus-core-stack\", \n        instance=\"192.0.100.1\"\n      }[5m]\n    ) == 0\n  )\n  and on (ifIndex, instance)\n  ifName{\n    job=\"ruckus-core-stack\",\n    instance=\"192.0.100.1\",\n    ifName=~\"ethernet 2/1/.*\"\n  }\n)\nor vector(0)",
     "legendFormat": "__auto",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"switch_port_metrics\" and\n    r._field == \"status\" and\n    r.switch == \"icx8100\"\n  )\n  |> group(columns: [\"port\"])\n  |> last()\n  |> filter(fn: (r) => r._value == 0)\n  |> group()\n  |> count()\n"
    }
   ]
  },
  {
   "title": "Switch 1 - Empty Ports",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "/ 24" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  (\n    max_over_time(\n      ifOperStatus{\n        job=\"ruckus-core-stack\",\n        instance=\"192.0.100.1\"\n      }[5m]\n    ) == 2\n  )\n  and on (ifIndex, instance)\n  ifName{\n    job=\"ruckus-core-stack\",\n    instance=\"192.0.100.1\",\n    ifName=~\"ethernet 2/1/.*\"\n  }\n)\nor vector(0)",
     "legendFormat": "__auto",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"switch_port_metrics\" and\n    r._field == \"status\" and\n    r.switch == \"icx8100\"\n  )\n  |> group(columns: [\"port\"])\n  |> last()\n  |> filter(fn: (r) => r._value == 2)\n  |> group()\n  |> count()\n"
    }
   ]
  },
  {
   "title": "Switch 1 - Ruckus ICX 8200",
   "type": "andrewbmchugh-flow-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max_over_time(\n  ifOperStatus{\n    job=\"ruckus-core-stack\",\n    instance=\"192.0.100.1\"\n  }[5m]\n)\n* on (ifIndex, instance) group_left(ifName)\nifName{\n  job=\"ruckus-core-stack\",\n  instance=\"192.0.100.1\",\n  ifName=~\"ethernet 1/1/.*\"\n}",
     "legendFormat": "{{ifName}}",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"switch_port_metrics\" and\n    r._field == \"status\" and\n    r.switch == \"icx8200\"\n  )\n  |> group(columns: [\"port\"])\n  |> last()\n  |> keep(columns: [\"_time\", \"_value\", \"port\"])\n"
    }
   ]
  },
  {
   "title": "Switch 1 - Ruckus ICX 8200",
   "type": "andrewbmchugh-flow-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "max_over_time(\n  ifOperStatus{\n    job=\"ruckus-core-stack\",\n    instance=\"192.0.100.1\"\n  }[5m]\n)\n* on (ifIndex, instance) group_left(ifName)\nifName{\n  job=\"ruckus-core-stack\",\n  instance=\"192.0.100.1\",\n  ifName=~\"ethernet 2/1/.*\"\n}",
     "legendFormat": "{{ifName}}",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"switch_port_metrics\" and\n    r._field == \"status\" and\n    r.switch == \"icx8200\"\n  )\n  |> group(columns: [\"port\"])\n  |> last()\n  |> keep(columns: [\"_time\", \"_value\", \"port\"])\n"
    }
   ]
  },
  {
   "title": "ICX 8100 - Access Switches Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }
  },
  {
   "title": "Access Switch 1 – Active Ports",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "/ 24" } },
   "targets": [
    {
     "expr": "count(\n  (\n    max_over_time(\n      ifOperStatus{\n        job=\"ruckus-access-switches\",\n        instance=\"192.0.100.3\"\n      }[5m]\n    )\n    * on (ifIndex, instance) group_left(ifName)\n    ifName{\n      job=\"ruckus-access-switches\",\n      instance=\"192.0.100.3\",\n      ifName=~\"ethernet 1/1/.*\"\n    }\n  ) == 1\n)\nor vector(0)\n",
     "legendFormat": "__auto",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"switch_port_metrics\" and\n    r._field == \"status\" and\n    r.switch == \"icx8200\"\n  )\n  |> group(columns: [\"port\"])\n  |> last()\n  |> filter(fn: (r) => r._value == 1)\n  |> group()\n  |> count()\n"
    }
   ]
  },
  {
   "title": "Access Switch 1 – Down Ports",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "/ 24" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  (\n    max_over_time(\n      ifOperStatus{\n        job=\"ruckus-access-switches\",\n        instance=\"192.0.100.3\"\n      }[5m]\n    )\n    * on (ifIndex, instance) group_left(ifName)\n    ifName{\n      job=\"ruckus-access-switches\",\n      instance=\"192.0.100.3\",\n      ifName=~\"ethernet 1/1/.*\"\n    }\n  ) == 0\n)\nor vector(0)\n",
     "legendFormat": "__auto",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"switch_port_metrics\" and\n    r._field == \"status\" and\n    r.switch == \"icx8200\"\n  )\n  |> group(columns: [\"port\"])\n  |> last()\n  |> filter(fn: (r) => r._value == 0)\n  |> group()\n  |> count()\n"
    }
   ]
  },
  {
   "title": "Access Switch 1 - Empty Ports",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "/ 24" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  (\n    max_over_time(\n      ifOperStatus{\n        job=\"ruckus-access-switches\",\n        instance=\"192.0.100.3\"\n      }[5m]\n    )\n    * on (ifIndex, instance) group_left(ifName)\n    ifName{\n      job=\"ruckus-access-switches\",\n      instance=\"192.0.100.3\",\n      ifName=~\"ethernet 1/1/.*\"\n    }\n  ) == 2\n)\nor vector(0)\n",
     "legendFormat": "{{ifName}}",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"switch_port_metrics\" and\n    r._field == \"status\" and\n    r.switch == \"icx8200\"\n  )\n  |> group(columns: [\"port\"])\n  |> last()\n  |> filter(fn: (r) => r._value == 2)\n  |> group()\n  |> count()\n"
    }
   ]
  },
  {
   "title": "Server Switch – Active Ports",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "/ 24" } },
   "targets": [
    {
     "expr": "count(\n  (\n    max_over_time(\n      ifOperStatus{\n        job=\"ruckus-access-switches\",\n        instance=\"192.0.100.4\"\n      }[5m]\n    )\n    * on (ifIndex, instance) group_left(ifName)\n    ifName{\n      job=\"ruckus-access-switches\",\n      instance=\"192.0.100.4\",\n      ifName=~\"ethernet 1/1/.*\"\n    }\n  ) == 1\n)\nor vector(0)\n",
     "legendFormat": "__auto",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"switch_port_metrics\" and\n    r._field == \"status\" and\n    r.switch == \"icx8200\"\n  )\n  |> group(columns: [\"port\"])\n  |> last()\n  |> filter(fn: (r) => r._value == 1)\n  |> group()\n  |> count()\n"
    }
   ]
  },
  {
   "title": "Server Switch – Down Ports",
   "type": "stat",
   "description": "Server access switch ",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "/ 24" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  (\n    max_over_time(\n      ifOperStatus{\n        job=\"ruckus-access-switches\",\n        instance=\"192.0.100.4\"\n      }[5m]\n    )\n    * on (ifIndex, instance) group_left(ifName)\n    ifName{\n      job=\"ruckus-access-switches\",\n      instance=\"192.0.100.4\",\n      ifName=~\"ethernet 1/1/.*\"\n    }\n  ) == 0\n)\nor vector(0)\n",
     "legendFormat": "__auto",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"switch_port_metrics\" and\n    r._field == \"status\" and\n    r.switch == \"icx8200\"\n  )\n  |> group(columns: [\"port\"])\n  |> last()\n  |> filter(fn: (r) => r._value == 0)\n  |> group()\n  |> count()\n"
    }
   ]
  },
  {
   "title": "Server Switch - Empty Ports",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "/ 24" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  (\n    max_over_time(\n      ifOperStatus{\n        job=\"ruckus-access-switches\",\n        instance=\"192.0.100.4\"\n      }[5m]\n    )\n    * on (ifIndex, instance) group_left(ifName)\n    ifName{\n      job=\"ruckus-access-switches\",\n      instance=\"192.0.100.4\",\n      ifName=~\"ethernet 1/1/.*\"\n    }\n  ) == 2\n)\nor vector(0)\n",
     "legendFormat": "{{ifName}}",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"switch_port_metrics\" and\n    r._field == \"status\" and\n    r.switch == \"icx8200\"\n  )\n  |> group(columns: [\"port\"])\n  |> last()\n  |> filter(fn: (r) => r._value == 2)\n  |> group()\n  |> count()\n"
    }
   ]
  },
  {
   "title": "Switch 1 - Ruckus ICX 8200",
   "type": "andrewbmchugh-flow-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "max_over_time(\n  ifOperStatus{\n    job=\"ruckus-access-switches\",\n    instance=\"192.0.100.3\"\n  }[5m]\n)\n* on (ifIndex, instance) group_left(ifName)\nifName{\n  job=\"ruckus-access-switches\",\n  instance=\"192.0.100.3\",\n  ifName=~\"ethernet 1/1/.*\"\n}",
     "legendFormat": "{{ifName}}",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"switch_port_metrics\" and\n    r._field == \"status\" and\n    r.switch == \"icx8200\"\n  )\n  |> group(columns: [\"port\"])\n  |> last()\n  |> keep(columns: [\"_time\", \"_value\", \"port\"])\n"
    }
   ]
  },
  {
   "title": "Switch 1 - Ruckus ICX 8200",
   "type": "andrewbmchugh-flow-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "max_over_time(\n  ifOperStatus{\n    job=\"ruckus-access-switches\",\n    instance=\"192.0.100.4\"\n  }[5m]\n)\n* on (ifIndex, instance) group_left(ifName)\nifName{\n  job=\"ruckus-access-switches\",\n  instance=\"192.0.100.4\",\n  ifName=~\"ethernet 1/1/.*\"\n}",
     "legendFormat": "{{ifName}}",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"switch_port_metrics\" and\n    r._field == \"status\" and\n    r.switch == \"icx8200\"\n  )\n  |> group(columns: [\"port\"])\n  |> last()\n  |> keep(columns: [\"_time\", \"_value\", \"port\"])\n"
    }
   ]
  },
  {
   "title": "Access Points Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total APs Inventory",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 166 },
     "targets": [
      {
       "expr": "ruckusUnleashedWLANAPStatus",
       "legendFormat": "__auto",
       "query": "from(bucket: \"my-bucket\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"ruckus_ap_metrics\" and\n    r._field == \"channel_utilization_5ghz\"\n  )\n  |> group(columns: [\"ap_name\"])\n  |> last()\n  |> filter(fn: (r) => r._value > 75)\n  |> group()\n  |> count()\n"
      }
     ]
    },
    {
     "title": "Online APs / Total APs",
     "type": "stat",
     "gridPos": { "h": 10, "w": 7, "x": 12, "y": 166 },
     "fieldConfig": { "defaults": { "unit": "/ 4" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ruckusUnleashedWLANAPStatus)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Offline APs",
     "type": "stat",
     "gridPos": { "h": 10, "w": 5, "x": 19, "y": 166 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(ruckusUnleashedWLANAPStatus) - sum(ruckusUnleashedWLANAPStatus)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Offline AP Details",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 241 },
     "targets": [
      {
       "expr": "ruckusUnleashedWLANAPStatus == 0",
       "legendFormat": "__auto",
       "query": "from(bucket: \"my-bucket\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"ruckus_ap_metrics\" and\n    r._field == \"status\"\n  )\n  |> group(columns: [\"ap_name\"])\n  |> last()\n  |> filter(fn: (r) => r._value == 0)\n  |> group()\n  |> keep(columns: [\"ap_name\", \"_time\"])\n  |> sort(columns: [\"ap_name\"])\n"
      }
     ]
    },
    {
     "title": "Online AP Details",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 241 },
     "targets": [
      {
       "expr": "ruckusUnleashedWLANAPStatus == 1",
       "legendFormat": "__auto",
       "query": "from(bucket: \"my-bucket\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"ruckus_ap_metrics\" and\n    r._field == \"status\"\n  )\n  |> group(columns: [\"ap_name\"])\n  |> last()\n  |> filter(fn: (r) => r._value == 0)\n  |> group()\n  |> keep(columns: [\"ap_name\", \"_time\"])\n  |> sort(columns: [\"ap_name\"])\n"
      }
     ]
    },
    {
     "title": "Slow APs Details",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 250 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "min(up{device_role=\"core\"})",
       "legendFormat": "__auto",
       "query": "last_utilization = from(bucket: \"my-bucket\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"ruckus_ap_metrics\" and r._field == \"channel_utilization_5ghz\")\n  |> group(columns: [\"ap_name\"])\n  |> last()\n  |> filter(fn: (r) => r._value > 75)\n  |> keep(columns: [\"ap_name\", \"_value\"])\n  |> rename(columns: {_value: \"utilization\"})\n\nlast_client_count = from(bucket: \"my-bucket\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"ruckus_ap_metrics\" and r._field == \"client_count\")\n  |> group(columns: [\"ap_name\"])\n  |> last()\n  |> keep(columns: [\"ap_name\", \"_value\"])\n  |> rename(columns: {_value: \"clients\"})\n\njoin(\n  tables: {util: last_utilization, clients: last_client_count},\n  on: [\"ap_name\"]\n)\n|> sort(columns: [\"utilization\"], desc: true)\n|> group()\n"
      }
     ]
    },
    {
     "title": "Slow APs (High Utilization)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 12, "y": 250 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"my-bucket\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"ruckus_ap_metrics\" and\n    r._field == \"channel_utilization_5ghz\"\n  )\n  |> group(columns: [\"ap_name\"])\n  |> last()\n  |> filter(fn: (r) => r._value > 75)\n  |> group()\n  |> count()\n"
      }
     ]
    }
   ]
  },
  { "title": "Temperature Sensor Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Temperature Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "modbus_temperature_celsius{device=\"172.16.2.49\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ambient Room Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "modbus_temperature_celsius{device=\"172.16.2.49\"}",
     "legendFormat": "__auto",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -10m)\n  |> filter(fn: (r) =>\n    r._measurement == \"environment\" and\n    r._field == \"temperature\" and\n    r.location == \"server_room\"\n  )\n  |> group()\n  |> last()\n"
    }
   ]
  },
  {
   "title": "Average Temperature (last 24h)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(modbus_temperature_celsius{device=\"172.16.2.49\"}[24h])",
     "legendFormat": "__auto",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -24h)\n  |> filter(fn: (r) =>\n    r._measurement == \"environment\" and\n    r._field == \"temperature\" and\n    r.location == \"server_room\"\n  )\n  |> group()\n  |> mean()\n"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "modbus_temperature_celsius{device=\"172.16.2.49\"}",
     "legendFormat": "__auto",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"environment\" and\n    r._field == \"temperature\" and\n    r.location == \"server_room\"\n  )\n  |> group()\n  |> aggregateWindow(\n    every: v.windowPeriod,\n    fn: mean,\n    createEmpty: false\n  )\n  |> yield(name: \"mean_temperature\")\n"
    }
   ]
  },
  {
   "title": "Max Temperature (last 24h)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(modbus_temperature_celsius{device=\"172.16.2.49\"}[24h])",
     "legendFormat": "__auto",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -24h)\n  |> filter(fn: (r) =>\n    r._measurement == \"environment\" and\n    r._field == \"temperature\" and\n    r.location == \"server_room\"\n  )\n  |> max()\n"
    }
   ]
  },
  {
   "title": "Min Temperature (last 24h)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min_over_time(modbus_temperature_celsius{device=\"172.16.2.49\"}[24h])",
     "legendFormat": "__auto",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -24h)\n  |> filter(fn: (r) =>\n    r._measurement == \"environment\" and\n    r._field == \"temperature\" and\n    r.location == \"server_room\"\n  )\n  |> group()\n  |> min()\n"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "modbus_humidity_percent{device=\"172.16.2.49\"}",
     "legendFormat": "__auto",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"environment\" and\n    r._field == \"humidity\" and\n    r.location == \"server_room\"\n  )\n  |> group()\n  |> aggregateWindow(\n    every: v.windowPeriod,\n    fn: mean,\n    createEmpty: false\n  )\n  |> yield(name: \"mean\")\n"
    }
   ]
  },
  {
   "title": "Ambient Room Humidity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "modbus_humidity_percent{device=\"172.16.2.49\"}",
     "legendFormat": "__auto",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -10m)\n  |> filter(fn: (r) =>\n    r._measurement == \"environment\" and\n    r._field == \"humidity\" and\n    r.location == \"server_room\"\n  )\n  |> group()\n  |> last()\n"
    }
   ]
  },
  {
   "title": "Humidity Trend (24h)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(modbus_humidity_percent{device=\"172.16.2.49\"}[24h])",
     "legendFormat": "__auto",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"environment\" and\n    r._field == \"humidity\" and\n    r.location == \"server_room\"\n  )\n  |> group()\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Server Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Utilization",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 387 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 * (\n    hrStorageUsed{job=\"snmp-servers\", hrStorageIndex=\"1\"}\n  /\n    hrStorageSize{job=\"snmp-servers\", hrStorageIndex=\"1\"}\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Usage %",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 387 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (instance) (hrProcessorLoad{job=\"snmp-servers\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 387 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by(instance) (hrProcessorLoad{job=\"snmp-servers\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": " CPU Utilization panel",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 407 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "hrProcessorLoad{job=\"snmp-servers\"}",
       "legendFormat": "CPU {{hrProcessorIndex}}"
      }
     ]
    },
    {
     "title": "Network",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 417 },
     "targets": [
      {
       "expr": "100 * (\n  hrStorageUsed{job=\"snmp-servers\", hrStorageDescr=~\"/.*\"}\n  / \n  hrStorageSize{job=\"snmp-servers\", hrStorageDescr=~\"/.*\"}\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Utilization panel",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 417 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * (hrStorageUsed{job=\"snmp-servers\", hrStorageIndex=\"1\"} / hrStorageSize{job=\"snmp-servers\", hrStorageIndex=\"1\"})",
       "legendFormat": "Memory"
      },
      {
       "expr": "100 * (hrStorageUsed{job=\"snmp-servers\", hrStorageIndex=\"10\"} / hrStorageSize{job=\"snmp-servers\", hrStorageIndex=\"10\"})",
       "legendFormat": "Swap"
      }
     ]
    }
   ]
  },
  {
   "title": "MSSQL Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "MSSQL CPU Wait (SOS_SCHEDULER_YIELD)",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 8, "x": 0, "y": 388 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "delta(mssql_cpu_wait_ms[30m])", "legendFormat": "{{target}}" }
     ]
    },
    {
     "title": "MSSQL Lock Wait (LCK_M_)",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 8, "x": 8, "y": 388 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "delta(mssql_lock_wait_ms[10m])", "legendFormat": "{{target}}" }
     ]
    },
    {
     "title": "MSSQL Disk Wait (PAGEIOLATCH)",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 8, "x": 16, "y": 388 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "delta(mssql_disk_wait_ms[10m])", "legendFormat": "{{target}}" }
     ]
    }
   ]
  }
 ]
}